version: '2'

services:
  web:
    image: nginx:alpine
    command: nginx
    restart: always
    mem_limit: 512M
    ports:
      - "8080:80/tcp"
    links:
      - app
    volumes_from:
      - app
    depends_on:
      - app

  app:
    image: slavoutich/nextcloud-fpm:13.0.1.0
    restart: always
    mem_limit: 2048M
    expose:
      - "9000"
    links:
      - redis
      - db
    volumes_from:
      - storage
    env_file:
      - db.env
    depends_on:
      - redis
      - db

  db:
    image: postgres:9.6-alpine
    restart: always
    mem_limit: 256M
    expose:
      - 5432
    env_file:
      - db.env
    volumes_from:
      - storage

  redis:
    image: redis:3.2-alpine
    restart: always
    mem_limit: 128M
    expose:
      - 6379

  storage:
    image: alpine:latest
    command: /bin/sh
    mem_limit: 128M
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ***MY_DATA_FOLDER***/config:/var/www/html/config
      - ***MY_DATA_FOLDER***/data:/var/www/html/data
      - ***MY_DATA_FOLDER***/custom_apps:/var/www/html/custom_apps
      - ***MY_DATA_FOLDER***/pgdb:/var/lib/postgresql/data
